name: Flutter iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod install

    - name: Fetch Dependencies
      run: flutter pub get

    - name: Build iOS App
      run: flutter build ios --release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iOS-IPA
        path: build/ios/iphoneos/Runner.app
